### ISSUE TITLE
Set up repo per course instructions

### ISSUE THREAD

**Issue by Kibrael** [berkleysayaka/DATA205-berkleysayaka#1]
@berkleysayaka 
### Requirements
- [x] Repository named Data205
- [x] project board set up with milestones outlined below
<img width="1346" alt="data 205 milestones" src="https://github.com/user-attachments/assets/70135c88-2f8f-4b9e-a431-e32d094135a4">
- [ ] readme with a draft of project outline, should provide context to readers and address required aspects of the project.

#### Readme Requirements
- Must access data from an original data source
- Not from Kaggle or another aggregator, unless you can trace the data back to its primary source and access it there
- Must choose and use data in a manner consistent with any licensing or usage restrictions
- Must use real-world data (not synthetic data)
- Must work with at least 2 quantitative (numerical) and 2 qualitative (categorical) variables
- Additional data requirements will be discussed as you refine your project ideas

**Comment by berkleysayaka** [comment]
Updated repo name; https://github.com/berkleysayaka/DATA205-berkleysayaka

**Comment by berkleysayaka** [comment]
### Milestones: 

1.	10/23 Submit the Project plan and creating a slide for presentation in the class Clarification of goals
2.	10/30 Start building modes/ Visualizations - Assumption of hypothesis
3.	11/6 Submit the models or visualizations 
4.	11/13 Working with Fraud patterns and creating a slide for presentation in the class Model construction /Model evaluation
5.	11/20 Analysis of specific regions or attributes - Model construction /Model evaluation
6.	12/4 Creating a rough draft – creating a slide for Dry Runs
7.	12/11 Submit final cleaned up GitHub repo
8.	12/18 Submit Final report and PowerPoint

**Comment by berkleysayaka** [comment]
Created milestones
